// show: himym | tbbt | friends | twilight | office (см. Logic.SHOWS)
// media: { type: 'image', src } | { type: 'audio', src } | { type: 'text', text }  — текст только когда нет картинки/звука
// question: главный вопрос на карточке (вместо «что за сериал?»), answer: ответ, который открывается тапом
// bonus: доп-вопросы ведущей после ответа; ответ открывается тапом
// loud: факт показывается капсом, жирным и крупно
// Порядок массива = порядок игры (без рандома): сериалы перемешаны вручную, финал — «леген…дарно».
// Все цитаты — в русском дубляже (Кураж-Бамбей, РТР/Парамаунт Комеди), звуки — тоже русские, кроме музыки.
const QUESTIONS = [
  {
    id: 'friends-pivot', show: 'friends', media: { type: 'image', src: 'assets/img/friends-pivot.jpg' },
    question: 'Что кричит Росс?',
    answer: '«Поворот! Поворот! ПОВОРОТ!»',
    bonus: [
      { q: 'Что несут?', a: 'Новый диван Росса по лестнице' },
      { q: 'Чем кончилось?', a: 'Диван распилили пополам. Магазин вернул 4 доллара' },
    ],
    fact: 'Чендлер в ответ: «Заткнись! Заткнись! ЗАТКНИСЬ!»',
  },
  {
    id: 'tbbt-bazinga', show: 'tbbt', media: { type: 'audio', src: 'assets/snd/tbbt-bazinga.mp3' },
    question: 'Кто так говорит и как это звучит в оригинале?',
    answer: 'Шелдон — «Базинга!»',
    bonus: [{ q: 'Когда он это говорит?', a: 'После своих «шуток» — чтобы все поняли, что это была шутка' }],
    fact: 'Впервые прозвучало в финале 2 сезона. Перевод — Кураж-Бамбей.',
  },
  {
    id: 'himym-umbrella', show: 'himym', media: { type: 'image', src: 'assets/img/himym-umbrella.jpg' },
    question: 'Кто в итоге окажется под этим зонтом?',
    answer: 'Тед и Трейси — та самая Мать',
    bonus: [{ q: 'Что символизирует зонт?', a: 'Судьбу: зонт кочует от Теда к Матери и обратно все 9 сезонов' }],
    fact: 'Главный символ сериала — именно по зонту Тед и находит Мать.',
  },
  {
    id: 'office-stapler', show: 'office', media: { type: 'image', src: 'assets/img/office-stapler.jpg' },
    question: 'Что происходит?',
    answer: 'Джим залил степлер Дуайта в желе',
    bonus: [{ q: 'В какой серии?', a: 'В самой первой' }],
    fact: 'Первая серия, первый розыгрыш — и Дуайт требует ответить «по всей строгости».',
  },
  {
    id: 'twilight-sparkle', show: 'twilight', media: { type: 'image', src: 'assets/img/twilight-sparkle.jpg' },
    question: 'Это...',
    answer: '«Это кожа убийцы, Белла»',
    bonus: [{ q: 'Что с ним происходит на солнце?', a: 'Сверкает' }],
    fact: 'Главный мем саги.',
  },
  {
    id: 'friends-smellycat', show: 'friends', media: { type: 'audio', src: 'assets/snd/friends-smellycat.mp3' },
    question: 'Кто поёт и как называется песня?',
    answer: 'Фиби Буффе — «Драный кот»',
    bonus: [{ q: 'Где она обычно выступает?', a: 'В «Централ Перк»' }],
    fact: '«Драный кот, драный кот, у тебя пустой живот…» В другом переводе — «Вонючий кот».',
  },
  {
    id: 'tbbt-knock', show: 'tbbt', media: { type: 'audio', src: 'assets/snd/tbbt-knock.mp3' },
    question: 'Кто так стучит и сколько раз?',
    answer: 'Шелдон — три серии по три',
    bonus: [{ q: 'Что будет, если открыть на первом стуке?', a: 'Достучит оставшиеся — в тебя' }],
    fact: 'Однажды Пенни открыла дверь на первом стуке — Шелдону пришлось достучать в неё.',
  },
  {
    id: 'himym-brocode', show: 'himym', media: { type: 'image', src: 'assets/img/himym-brocode.jpg' },
    question: 'Статья №1 этой книги',
    answer: '«Братаны важнее тёлок»',
    bonus: [{ q: 'Кто автор?', a: 'Барни Стинсон' }],
    fact: 'По легенде Барни, Кодекс написал Бенджамин Франклин в 1776 году.',
  },
  {
    id: 'office-bankruptcy', show: 'office', media: { type: 'image', src: 'assets/img/office-bankruptcy.jpg' },
    question: 'Я ... !',
    answer: '«Я объявляю банкротство!»',
    bonus: [{ q: 'В чём ошибка?', a: 'Он думал, что достаточно просто крикнуть это на весь офис' }],
    fact: 'Оскар: «Нельзя просто сказать слово „банкротство“ и ждать, что что-то произойдёт».',
  },
  {
    id: 'friends-omg', show: 'friends', media: { type: 'audio', src: 'assets/snd/friends-omg.mp3' },
    question: 'Кто это и чья она бывшая?',
    answer: 'Дженис — бывшая Чендлера',
    bonus: [{ q: 'Что у неё самое узнаваемое, кроме фразы?', a: 'Смех' }],
    fact: 'Самый узнаваемый смех на телевидении.',
  },
  {
    id: 'tbbt-sarcasm', show: 'tbbt', media: { type: 'image', src: 'assets/img/tbbt-sarcasm.jpg' },
    question: 'Почему?',
    answer: 'Шелдон не распознаёт сарказм — Леонард подсказывает табличкой',
    bonus: [{ q: 'Что Шелдон переспрашивает, когда научился?', a: '«Это был сарказм?»' }],
    fact: 'Позже Шелдон научился и стал спрашивать сам.',
  },
  {
    id: 'himym-horn', show: 'himym', media: { type: 'image', src: 'assets/img/himym-horn.jpg' },
    question: 'Кто украл эту валторну и для кого?',
    answer: 'Тед — для Робин',
    bonus: [{ q: 'Откуда украл?', a: 'Со стены ресторана на первом свидании' }],
    fact: 'В финале Тед снова приходит к Робин с синей валторной.',
  },
  {
    id: 'twilight-baseball', show: 'twilight', media: { type: 'image', src: 'assets/img/twilight-baseball.jpg' },
    question: 'Почему Каллены играют только в грозу?',
    answer: 'Гром заглушает удары по мячу',
    bonus: [{ q: 'Кто пришёл на игру?', a: 'Джеймс, Виктория и Лоран' }],
    fact: 'Играют под песню группы Muse.',
  },
  {
    id: 'office-shesaid', show: 'office', media: { type: 'audio', src: 'assets/snd/office-shesaid.mp3' },
    question: 'Чья это фирменная шутка?',
    answer: 'Майкла Скотта',
    bonus: [{ q: 'Когда он её вставляет?', a: 'После любой двусмысленной фразы — даже в кабинете кадровика' }],
    fact: 'Из-за этой шутки Майкл однажды угодил на разбор к отделу кадров — и пошутил ещё раз прямо там.',
  },
  {
    id: 'friends-howyoudoin', show: 'friends', media: { type: 'audio', src: 'assets/snd/friends-howyoudoin.mp3' },
    question: 'Чей это подкат?',
    answer: 'Джоуи Триббиани',
    bonus: [{ q: 'Работает?', a: 'Безотказно' }],
    fact: 'Фирменный подкат Джоуи.',
  },
  {
    id: 'tbbt-gravity', show: 'tbbt', media: { type: 'audio', src: 'assets/snd/tbbt-gravity.mp3' },
    question: 'Чья это фраза?',
    answer: 'Шелдона Купера',
    bonus: [{ q: 'Что происходит в этой сцене?', a: 'Шелдон и Леонард тащат коробку с мебелью Пенни по лестнице' }],
    fact: 'Одна из самых цитируемых реплик Шелдона.',
  },
  {
    id: 'himym-tattoo', show: 'himym', media: { type: 'image', src: 'assets/img/himym-tattoo.jpg' },
    question: 'У кого такая тату и почему?',
    answer: 'У Теда, на пояснице — по пьяни после расставания с Робин',
    bonus: [{ q: 'Как называл её Барни?', a: '«Клеймо шалавы»' }],
    fact: 'Сводить тату Тед пошёл к дерматологу Стелле — своей будущей (несостоявшейся) жене.',
  },
  {
    id: 'office-dwightimpression', show: 'office', media: { type: 'image', src: 'assets/img/office-dwightimpression.jpg' },
    question: 'Что говорит Джим в образе Дуайта?',
    answer: '«Медведи. Свёкла. „Звёздный крейсер Галактика“»',
    bonus: [{ q: 'Сколько стоил костюм?', a: '11 долларов' }],
    fact: 'Дуайт в ответ: «Кража личности — это не шутки, Джим!»',
  },
  {
    id: 'friends-break', show: 'friends', media: { type: 'text', text: '«У нас был перерыв!»' },
    question: 'Кто это кричит и кому?',
    answer: 'Росс — Рэйчел',
    bonus: [{ q: 'Кто прав?', a: 'Спор не решён за 10 сезонов — любой ответ с аргументом' }],
    fact: 'Главный спор сериала.',
  },
  {
    id: 'tbbt-softkitty', show: 'tbbt', media: { type: 'audio', src: 'assets/snd/tbbt-softkitty.mp3' },
    question: 'Кому поют эту песню и когда её можно петь?',
    answer: 'Шелдону — только когда он болеет!',
    bonus: [{ q: 'Кто спел её ему первой?', a: 'Пенни — в обмен на растирание груди мазью' }],
    fact: 'Песню Шелдону пела мама, когда он был маленьким.',
  },
  {
    id: 'twilight-spidermonkey', show: 'twilight', media: { type: 'image', src: 'assets/img/twilight-spidermonkey.jpg' },
    question: 'Держись..',
    answer: '«Держись крепче, мартышка»',
    bonus: [{ q: 'Куда лезут?', a: 'На дерево над лесом Форкса' }],
    fact: 'Фразу выбрал сам Роберт Паттинсон из нескольких вариантов. Другие варианты: «Приготовься к взлёту», «Ты ведь не боишься высоты?», «Крепко держишься?»',
    loud: true,
  },
  {
    id: 'himym-sonofabitch', show: 'himym', media: { type: 'text', text: '«Ах ты ж сукин сын!»' },
    question: 'Чьё это любимое ругательство?',
    answer: 'Лили',
    bonus: [{ q: 'Кому чаще всего достаётся?', a: 'Барни' }],
    fact: 'Лили говорит это почти в каждом сезоне.',
  },
  {
    id: 'office-prisonmike', show: 'office', media: { type: 'image', src: 'assets/img/office-prisonmike.jpg' },
    question: 'Что, по словам Тюремного Майка, самое страшное в тюрьме?',
    answer: '«Дементоры»',
    bonus: [{ q: 'Зачем он это устроил?', a: 'Доказать, что в офисе лучше, чем в тюрьме' }],
    fact: 'Повод — новый сотрудник Мартин, который отсидел и сказал, что в тюрьме было неплохо.',
  },
  {
    id: 'friends-chandler-could', show: 'friends', media: { type: 'image', src: 'assets/img/friends-chandler-could.jpg' },
    question: 'Что говорит Джоуи в этой сцене? Процитируй!',
    answer: '«Могу ли я НАДЕТЬ ещё больше одежды?»',
    bonus: [
      { q: 'Кого пародирует?', a: 'Чендлера' },
      { q: 'Почему столько одежды?', a: 'Надел всю одежду Чендлера в отместку за спрятанное бельё' },
    ],
    fact: 'И всё это — без белья.',
  },
  {
    id: 'tbbt-temples', show: 'tbbt', media: { type: 'image', src: 'assets/img/tbbt-temples.jpg' },
    question: 'Что Шелдон пытается сделать?',
    answer: 'Взорвать голову Леонарда силой мысли',
    bonus: [{ q: 'С чем не путать?', a: 'С «унаги» Росса из «Друзей»' }],
    fact: 'Шелдон честно верит, что это возможно — просто нужна тренировка.',
  },
  {
    id: 'twilight-eyesonfire', show: 'twilight', media: { type: 'audio', src: 'assets/snd/twilight-eyesonfire.mp3' },
    question: 'В какой сцене фильма звучит эта песня?',
    answer: 'Белла ищет в интернете легенды о «холодных» — и едет с подругами в Порт-Анджелес',
    bonus: [{ q: 'Кто исполняет?', a: 'Blue Foundation — «Eyes on Fire»' }],
    fact: 'То самое «хао-хао» из Челябинска. Саундтрек первого фильма — сплошные хиты: Paramore, Muse, Iron & Wine.',
  },
  {
    id: 'himym-legendary', show: 'himym', media: { type: 'audio', src: 'assets/snd/himym-legendary.mp3' },
    question: 'Чья это фирменная фраза?',
    answer: 'Барни Стинсона',
    bonus: [{ q: 'Ещё две его фразы-мема?', a: '«Приоденься!» и «Вызов принят!»' }],
    fact: 'Любимое слово Барни — в озвучке Кураж-Бамбей.',
  },
];

if (typeof module !== 'undefined' && module.exports) module.exports = QUESTIONS;
